<a href="https://colab.research.google.com/github/ravinnd3/PyTorch_tut/blob/main/00_pytorch_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorial Link -> https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.9.0+cu126
False


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
# To enable CUDA for PyTorch, you need to change your Colab runtime type to GPU.
# Go to Runtime -> Change runtime type -> Hardware accelerator -> GPU, then click Save.
# After changing, re-run the first cell to verify torch.cuda.is_available() is True.

In [ ]:
# pip install nvidia-smi

In [ ]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.shape

torch.Size([])

In [ ]:
#get tensor as python int
scaler.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MAXTRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

**TENSOR.shape  -->  (1, 3, 3)**

That means:

Dimension 0 has size 1

Dimension 1 has size 3

Dimension 2 has size 3

So the valid indices for dim-0 are only:

TENSOR[0]   # works

TENSOR[1]   # crashes → because there is NO index 1

Brutal truth: you're trying to access an element that doesn't exist.

If you wanted two blocks (so that TENSOR[1] is valid), you needed something like:



```
TENSOR = torch.tensor([[[1,2,3],
     [3,6,9],
     [2,4,5]],

    [[10,11,12],
     [13,14,15],
     [16,17,18]]
])
```


Now the shape is (2, 3, 3) and TENSOR[1] works.

If your intention was just to index rows inside the single inner matrix, then you're mixing up dimensions:

TENSOR[0, 1]    # second row → [3,6,9]

TENSOR[0, 2]    # third row → [2,4,5]

To summarize the error :

Your tensor has only one “outer” element, so index 1 simply doesn't exist. The tensor layout is rigid, and PyTorch won't invent dimensions for you.



In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [ ]:
TENSOR[0][0][0]

tensor(1)

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
     [3,6,9],
     [2,4,5]],

    [[10,11,12],
     [13,14,15],
     [16,17,18]]
])

### Random tensors

Random tensors are importatnt because the way many NN learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` Start with random numbers->look at data->update random numbers -> look at data -> update random numbers```

In [ ]:
### Random tensors

In [ ]:
#create a random tensor of shape (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6077, 0.1133, 0.4456, 0.8957],
        [0.1445, 0.4405, 0.5255, 0.6209],
        [0.6033, 0.7090, 0.7846, 0.8784]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.9800, 0.2761, 0.9542, 0.5346],
         [0.7844, 0.0326, 0.5035, 0.9163],
         [0.6798, 0.3730, 0.9709, 0.8837]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.0388, 0.3312, 0.7555, 0.8407],
         [0.3183, 0.3344, 0.8455, 0.3661],
         [0.7885, 0.6844, 0.4492, 0.6700]],

        [[0.4187, 0.3512, 0.1748, 0.2431],
         [0.0859, 0.1270, 0.3881, 0.4182],
         [0.3078, 0.6925, 0.8122, 0.3300]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create random number with similar shape to an image tensor
# (height,width,color_channel with RGB)

random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_tensor

tensor([[[0.6934, 0.5136, 0.3014],
         [0.3246, 0.8296, 0.3308],
         [0.5881, 0.3076, 0.0638],
         ...,
         [0.5402, 0.4199, 0.3813],
         [0.9006, 0.5078, 0.6812],
         [0.9588, 0.1868, 0.2054]],

        [[0.1273, 0.8052, 0.7924],
         [0.1002, 0.4775, 0.6031],
         [0.2009, 0.3661, 0.4974],
         ...,
         [0.0367, 0.6034, 0.4516],
         [0.1683, 0.1684, 0.9163],
         [0.7612, 0.6034, 0.3456]],

        [[0.5282, 0.3830, 0.5649],
         [0.2738, 0.5960, 0.3069],
         [0.5047, 0.2109, 0.0070],
         ...,
         [0.4850, 0.1991, 0.1064],
         [0.4227, 0.3343, 0.6509],
         [0.5218, 0.3878, 0.2513]],

        ...,

        [[0.1975, 0.2398, 0.7214],
         [0.8078, 0.4265, 0.5429],
         [0.0734, 0.1920, 0.9603],
         ...,
         [0.3561, 0.2357, 0.9092],
         [0.2814, 0.7813, 0.9920],
         [0.2972, 0.9074, 0.0633]],

        [[0.2378, 0.7725, 0.5921],
         [0.9001, 0.9239, 0.3984],
         [0.

### Zeros and Ones

In [ ]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zero*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=1,end=11,step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
# creating tensors like
one_to_ten = torch.ones_like(input=one_to_ten)
one_to_ten

tensor([1, 1, 1, 1, 1])

In [ ]:
one_to_ten = torch.zeros_like(input=one_to_ten)
one_to_ten

tensor([0, 0, 0, 0, 0])

### Tensors datatype

Note : Tensors datatypes is one of the 3 big errors you will run into with pytorch & deep learning:

1.   Tensors not right datatypes
2.   Tensors not right shape
3.   Tensors not on the right device



In [ ]:
float32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float32_tensor.dtype

### deafult dtype is float32 as still none is passed

torch.float32

In [ ]:
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None,  # what datatype is the tensors
                              device=None, # What device your tensor on
                              requires_grad=False) # Whether or not to track gradient values
print(float32_tensor)
print(float32_tensor.dtype)
print(float32_tensor.device)
print(float32_tensor.requires_grad)

tensor([3., 6., 9.])
torch.float32
cpu
False


In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int32_tensor = float16_tensor.type(torch.int32)
int32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Matrix Multiplication

1. Element wise
2. Matrix multiplication (dot product)


In [ ]:
# Elemnt wise multiplication

tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])

print(tensor1, "*", tensor2)
print(f"Equals: {tensor1 * tensor2}")

tensor([1, 2, 3]) * tensor([4, 5, 6])
Equals: tensor([ 4, 10, 18])


In [ ]:
## Matrix Multiplication (dot product)

torch.matmul(tensor1,tensor2)

tensor(32)

### Finding min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(1,100,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
x.min() , x.max()

(tensor(1), tensor(91))

In [ ]:
x.mean()



RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
## So to fix above error needs to change the datatype


torch.mean(x.type(torch.float32))

tensor(46.)

In [ ]:
torch.sum(x)

tensor(460)

### Finding the positional min and max of tensors

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

### Reshaping, Stacking , Squeezing and unsqueezing tensors

1. Reshaping -> reshapes the tensors to defined tensor

2. view-> return the view of tensor of certain shape but keep the same memory as the original tensor

3. stacking -> combine multiple tensors on top of each other (vstack) or side by side (hstack)

4. squeeze -> removes all 1 dimensions from tensor

5. unsqueeze -> add a 1 dimension to a target tensor

6. permute -> Return a view of the input with dimensions permuted (swapped) in a certain way




In [ ]:
import torch


In [ ]:
x = torch.arange(1. , 10.)

x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#stack

x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
#stack

x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#stack

x_stacked = torch.stack([x,x,x,x],dim=2)
x_stacked

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### Indexing (selecting data from tensors)

In [7]:
## Indexing with pytorch is similar to numpy

x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [8]:
x.ndim

3

In [9]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
x[0][0]

tensor([1, 2, 3])

#squeeze -> removes all 1 dimensions from tensor

In [1]:
import torch

# Tensor with singleton dims: shape [3, 1, 2, 1, 4]
x = torch.randn(3, 1, 2, 1, 4)
print("Original:", x.shape)  # torch.Size([3, 1, 2, 1, 4])

y = torch.squeeze(x)         # Removes ALL size-1 dims
print("Squeezed:", y.shape)  # torch.Size([3, 2, 4])

z = torch.squeeze(x, dim=1)  # Only dim=1 (if size 1)
print("Dim 1 only:", z.shape) # torch.Size([3, 2, 1, 4])


Original: torch.Size([3, 1, 2, 1, 4])
Squeezed: torch.Size([3, 2, 4])
Dim 1 only: torch.Size([3, 2, 1, 4])


In [11]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
x_squeeze = torch.squeeze(x)
x_squeeze

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x_squeeze.ndim , x_squeeze.shape

(2, torch.Size([3, 3]))

In [14]:
x_squeeze_ = torch.squeeze(x_squeeze)
x_squeeze_

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#unsqueeze -> add a 1 dimension to a target tensor

In [16]:
a = torch.tensor([1, 2, 3])  # shape [3]
print("Vector:", a.shape)

b = a.unsqueeze(0)           # Add dim at pos 0 → row vector
print("Row:", b.shape)       # [1, 3]

c = a.unsqueeze(1)           # Add dim at pos 1 → column vector
print("Col:", c.shape)       # [3, 1]

# Broadcasting fix: 1D + 2D
d_2d = torch.tensor([[1,2,3],[4,5,6]])  # [2,3]
result = d_2d + a.unsqueeze(0)           # [1,3] + [2,3] → works!
print(result)


Vector: torch.Size([3])
Row: torch.Size([1, 3])
Col: torch.Size([3, 1])
tensor([[2, 4, 6],
        [5, 7, 9]])
