<a href="https://colab.research.google.com/github/ravinnd3/PyTorch_tut/blob/main/01_pytorch_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Running tensors and pytorch objects on the GPU , thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes

In [4]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# Count number of devices
torch.cuda.device_count()

1

# Putting tensors( and models ) on the GPU
## The reasons we want tensors/models on the GPU is because using GPU results in  faster computations.

In [8]:
# create a tensors (default is on CPU)
tensor = torch.tensor([1,2,3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
tensor = torch.tensor([1,2,3],device='cpu')

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor = torch.tensor([1,2,3],device='cuda')

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [11]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Moving tensors back to cpu

In [14]:
tensors_on_cpu = tensor.cpu().numpy()
tensors_on_cpu

array([1, 2, 3])